name: Update README Stats

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours (you can change this)
  workflow_dispatch:       # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
